import sys, os
import datetime

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.append(os.path.abspath('.'))

now = datetime.datetime.now()

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.todo', 'sphinx.ext.ifconfig', 'sphinx.ext.intersphinx', 'sphinx.ext.extlinks', 'hieroglyph']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_template']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Sphinx Theme Test'
copyright = u'{} Boundless'.format(now.year)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = str(now.year)
# The full version, including alpha/beta/rc tags.
release = str(now.year)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
today = ''

# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of documents that shouldn't be included in the build.
#unused_docs = []

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_patterns = []
exclude_patterns = ['**slides']
if tags.has('scormintro'):
  exclude_patterns.append('[0-9][0-9]**')

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

#External links
extlinks = {
    # boundless server
    'server': ('http://server.boundlessgeo.com/docs/latest/%s',''),
    'geoserver': ('http://server.boundlessgeo.com/docs/latest/geoserver/%s',''),
    'geos': ('https://osgeo-org.atlassian.net/browse/GEOS-%s','GEOS-'),
    'geot': ('https://osgeo-org.atlassian.net/browse/GEOT-%s','GEOT-'),
    'openlayers': ('https://openlayers.org/en/latest/%s',''),
    'postgresql': ('http://www.postgresql.org/docs/current/static/%s',''),
    'postgis': ('http://postgis.net/docs/manual-2.4/%s',''),

    # boundless desktop
    'desktop': ('https://connect.boundlessgeo.com/docs/desktop/latest/%s',''),
    'qgis': ('https://docs.qgis.org/2.18/en/docs/%s',''),
    'pgadmin': ('https://www.pgadmin.org/docs/pgadmin4/1.x/%s',''),
    'gdal': ('http://www.gdal.org/%s',''),
    'ogr': ('http://www.gdal.org/$s',''),

    # boundless customer
    'egnyte-files': ('https://boundlessgeo.egnyte.com/dl/%s',''),
    'training-files': ('http://training-files.boundlessgeo.com/%s',''),
    'connect': ('https://connect.boundlessgeo.com/%s',''),
    'leaning-center': ('https://learning-center.boundlessgeo.com/%s',''),

    # internal
    'sphinx': ('http://www.sphinx-doc.org/en/master/%s','')
}

# -- Options for HTML output ---------------------------------------------------


# The theme to use for HTML and HTML Help pages.  Major themes that come with
# Sphinx are currently 'default' and 'sphinxdoc'.
html_theme = 'learning_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['../..']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = 

html_short_title = "Test"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
html_use_modindex = False

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False
html_copy_source = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# If nonempty, this is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = ''

# Output file base name for HTML help builder.
htmlhelp_basename = "Test"

# -- Options for Hieroglyph output ---------------------------------------------

slide_title = project

autoslides = False
slide_theme = 'boundless_slides'
subtitle = 'Slide sub title'
slide_footer = 'slide footer'
slide_levels = 4
slide_numbers = True
# slide_theme_options = {'custom_css': 'boundless_slides.css'}


# requires html and slides build
slide_link_to_html = True
slide_link_html_to_slides = True
slide_link_html_sections_to_slides = True
slide_relative_path = '../slides/'
slide_html_relative_path = '../html/' 
slide_html_slide_link_symbol = '§'

# slide2 options

# slide_theme_options = {
#     'presenters': [
#         {
#             'name': 'Boundless Training',
#             'twitter': '@boundlessgeo',
#             'www': 'http://boundlessgeo.com/training',
#             'github': 'http://github.com/boundlessgeo/workshops'
#         },
#     ],
# }

# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
#latex_paper_size = 'letter'

# The font size ('10pt', '11pt' or '12pt').
latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'test.tex', project, u'Boundless Training', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = 'img/learning-logo-color.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

latex_elements = {
  'fontpkg': '\\usepackage{palatino}',
  'fncychap': '\\usepackage[Sonny]{fncychap}',
  'figure_align': 'H',
  'preamble': '''
      \\usepackage{graphicx,fancybox,letltxmacro}
      \\usepackage[export]{adjustbox}
      \\setlength\\fboxsep{0pt}
      \\setlength\\fboxrule{1pt}
      
      \\let\\OLDincludegraphics\\includegraphics
      
      \\renewcommand{\\includegraphics}[2][]{
        \\shadowbox{\\OLDincludegraphics[keepaspectratio=true,scale = 0.75,max width=4in,#1]{#2}}}
      
''',
}

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_use_modindex = False
